server:
  port: 8025
spring:
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.pass}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    enabled: true
    cache: false
  mail:
    name: i记账
    host: ${email.host}
    username: ${email.user}
    password: ${email.pass}
    properties:
      mail:
        debug: true
        smtp:
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false