spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ibk
    username: ibk
    password: i123b456k
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    enabled: true
    cache: false
  mail:
    name: i记账
    host: smtp.exmail.qq.com
    username: admin@stustyle.cn
    password: jScts7htwS7xj7r4
    properties:
      mail:
        debug: true
        smtp:
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
